### PR TITLE
Update release docs

### PR DESCRIPTION
**Pull request by dhaiducek**
- Dynamically determine names of remotes
- Reflow doc

### CODE REVIEW

**Review by yiraeChristineKim — APPROVED** [review]

**Comment by yiraeChristineKim** [comment]
I forgot where the [new-release] branch was created. Does it happen on CI?

**Comment by dhaiducek** [comment]
Yes, once the `main` branch is tagged with the version, it fast-forwards to the release branch (or creates it if it doesn't exist).

**Comment by dhaiducek** [comment]
For reference, that's this chunk in the release workflow:
https://github.com/stolostron/gatekeeper-operator/blob/5fae36f039535b0288dbf083f6d005231256ef4e/.github/workflows/release.yaml#L65-L78

**Comment by yiraeChristineKim** [comment]
> Yes, once the `main` branch is tagged with the version, it fast-forwards to the release branch (or creates it if it doesn't exist).

Thanks Dale!!

**Pull request merged**
